import turtle

#Letra Y
tortuga=turtle.Turtle()
tortuga.speed(100)
tortuga.pensize(12)
tortuga.color("black")
tortuga.shape('turtle')
tortuga.left(90)
tortuga.forward(90)
tortuga.left(30)
tortuga.forward(70)
tortuga.penup()
tortuga.right(180)
tortuga.forward(70)
tortuga.pendown()
tortuga.left(120)
tortuga.forward(70)

#Letra E
tortuga.penup()
tortuga.goto(60,0)
tortuga.pendown()
tortuga.color("Red")
tortuga.left(30)
tortuga.forward(150)
tortuga.right(90)
tortuga.forward(60)
tortuga.penup()
tortuga.goto(60,0)
tortuga.pendown()
tortuga.forward(60)
tortuga.penup()
tortuga.goto(60,0)
tortuga.left(90)
tortuga.forward(75)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(50)

#Letra R
tortuga.penup()
tortuga.goto(140,0)
tortuga.pendown()
tortuga.color("orange")
tortuga.left(90)
tortuga.forward(150)
tortuga.right(180)
tortuga.penup()
tortuga.forward(80)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(30)
tortuga.circle(40,180)
tortuga.forward(30)
tortuga.left(90)
tortuga.penup()
tortuga.forward(80)
tortuga.left(90)
tortuga.forward(30)
tortuga.circle(40,15)
tortuga.right(75)
tortuga.pendown()
tortuga.forward(80)

#Letra E
tortuga.penup()
tortuga.goto(240,0)
tortuga.pendown()
tortuga.color("Red")
tortuga.left(150)
tortuga.forward(150)
tortuga.right(90)
tortuga.forward(60)
tortuga.penup()
tortuga.goto(240,0)
tortuga.pendown()
tortuga.forward(60)
tortuga.penup()
tortuga.goto(240,0)
tortuga.left(90)
tortuga.forward(75)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(50)

#Letra L
tortuga.penup()
tortuga.goto(330,0)
tortuga.pendown()
tortuga.color("Blue")
tortuga.forward(65)
tortuga.penup()
tortuga.goto(330,0)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(150)

#Letra E
tortuga.penup()
tortuga.goto(420,0)
tortuga.pendown()
tortuga.color("Red")
tortuga.forward(150)
tortuga.right(90)
tortuga.forward(60)
tortuga.penup()
tortuga.goto(420,0)
tortuga.pendown()
tortuga.forward(60)
tortuga.penup()
tortuga.goto(420,0)
tortuga.left(90)
tortuga.forward(75)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(50)

#Letra I
tortuga.penup()
tortuga.goto(510,0)
tortuga.pendown()
tortuga.color("green")
tortuga.forward(60)
tortuga.penup()
tortuga.goto(510,0)
tortuga.forward(30)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(150)
tortuga.penup()
tortuga.goto(510,150)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(60)

#Letra D
tortuga.penup()
tortuga.goto(600,0)
tortuga.pendown()
tortuga.color("purple")
tortuga.forward(30)
tortuga.circle(75,180)
tortuga.forward(30)
tortuga.left(90)
tortuga.forward(150)

#Letra I
tortuga.penup()
tortuga.goto(710,0)
tortuga.pendown()
tortuga.color("green")
tortuga.left(90)
tortuga.forward(60)
tortuga.penup()
tortuga.goto(710,0)
tortuga.forward(30)
tortuga.pendown()
tortuga.left(90)
tortuga.forward(150)
tortuga.penup()
tortuga.goto(710,150)
tortuga.pendown()
tortuga.right(90)
tortuga.forward(60)

#Letra S
tortuga.penup()
tortuga.goto(830,75)
tortuga.pendown()
tortuga.color("yellow")
tortuga.circle(37.5,-250)
tortuga.penup()
tortuga.goto(830,77)
tortuga.pendown()
tortuga.left(65)
tortuga.circle(40,-240)

#Cuadrado
tortuga.penup()
tortuga.goto(-120,-100)
tortuga.pendown()
tortuga.color("brown")
tortuga.left(65)
tortuga.forward(1110)
tortuga.left(90)
tortuga.forward(340)
tortuga.left(90)
tortuga.forward(1110)
tortuga.left(90)
tortuga.forward(340)